env:
    OEM: oneplus
    CODENAME: avicii
    CIRRUS_CI: true
    CIRRUS_SHELL: bash
    TARGET: recoveryimage
    ROM_NAME: rising
    PRODUCT_NAME: lineage_avicii
    VARIANT: userdebug
    ROM_REPO: "https://github.com/RisingTechOSS/android"
    ROM_BRANCH: thirteen
    DEVICE_REPO: "https://github.com/Sanju0910/android_device_oneplus_avicii-risingos"
    DEVICE_BRANCH: tiramisu
    VENDOR_REPO: "https://gitlab.com/Sanju0910/android_vendor_oneplus_avicii"
    VENDOR_BRANCH: main
    KERNEL_REPO: "https://github.com/Sanju0910/android_kernel_oneplus_avicii"
    KERNEL_BRANCH: tiramisu
    HARDWARE_REPO: "https://github.com/Sanju0910/android_hardware_oplus"
    HARDWARE_BRANCH: tiramisu
    USERNAME: Sanju0910
    USERMAIL: sreeshankar0910@gmail.com
    
task:
  name: "Recovery Build"
  timeout_in: 240m
  trigger_type: manual
  container:
      image: ghcr.io/sanju0910/ubuntu:latest
      cpu: 8
      memory: 32G
      
 # CLONE_SCRIPT_script: |
#    if [ -z "$CIRRUS_PR" ]; then
#      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
   #   git reset --hard $CIRRUS_CHANGE_IN_REPO
#    else
    #  git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
   #   git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
   #   git reset --hard $CIRRUS_CHANGE_IN_REPO
#    fi    

  SYNC_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/sync_rom.sh | bash
      
  BUILD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/build_rom.sh | bash
      
  UPLOAD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/upload_rom.sh | bash
