env:
    OEM: oneplus
    CODENAME: avicii
    CIRRUS_CI: true
    CIRRUS_SHELL: bash
    TARGET: recoveryimage
    CR_NAME: orangefox
    USERNAME: Sanju0910
    USERMAIL: sreeshankar0910@gmail.com
    
task:
  name: "Recovery Build"
  timeout_in: 240m
  trigger_type: manual
  container:
      image: ghcr.io/sanju0910/ubuntu:latest
      cpu: 8
      memory: 32G
      
 # CLONE_SCRIPT_script: |
  #  if [ -z "$CIRRUS_PR" ]; then
#      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git reset --hard $CIRRUS_CHANGE_IN_REPO
 #   else
    #  git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
 #     git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
   #   git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  fi    

  SYNC_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/sync_orangefox_recovery.sh | bash
      
  BUILD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/build_recovery.sh | bash
      
  UPLOAD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/upload_recovery.sh | bash
